package utils

var (
	// APIVersion ...
	APIVersion = "1.0.0"
	// APIName ...
	APIName = "Droll GraphQL API"
	// ComicsSupported ...
	ComicsSupported = []string{XKCDComicName}
	// Limit ...
	Limit = 10

	// XKCDComicName ...
	XKCDComicName = "xkcd"
	// XKCDBaseAPIURL ...
	XKCDBaseAPIURL = "https://xkcd.com/"
	// XKCDBaseAPIPath ...
	XKCDBaseAPIPath = "/info.0.json"
	// XKCDStartIndex ...
	XKCDStartIndex = 1
)
